name: "podcast Generator"
author: "Ray Villalobos"
descriptions: "Generates a feed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    descriptipn: The commiter's email address
    required: true
    default: $ {{ githu.actor }}@localhost
  name:
    description: The committer's name
    required: true
    default: ${{ github.actor }}